# Data Preprocessing

In [1]:
!pip install keras-tuner

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting keras-tuner
  Downloading keras_tuner-1.3.0-py3-none-any.whl (167 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.3/167.3 KB 3.0 MB/s eta 0:00:00
Requirement already satisfied: packaging in /usr/local/lib/python3.9/dist-packages (from keras-tuner) (23.0)
Requirement already satisfied: tensorflow>=2.0 in /usr/local/lib/python3.9/dist-packages (from keras-tuner) (2.11.0)
Requirement already satisfied: ipython in /usr/local/lib/python3.9/dist-packages (from keras-tuner) (7.9.0)
Requirement already satisfied: requests in /usr/local/lib/python3.9/dist-packages (from keras-tuner) (2.25.1)
Collecting kt-legacy
  Downloading kt_legacy-1.0.4-py3-none-any.whl (9.6 kB)
Requirement already satisfied: tensorflow-estimator<2.12,>=2.11.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow>=2.0->keras-tuner) (2.11.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/lib/python3.9/dist-packages (from tensorflow>=2.0->keras-tuner) (0.2.0)
Requirement already satisfied: gast<=0.4.0,>=0.2.1 in /usr/local/lib/python3.9/dist-packages (from tensorflow>=2.0->keras-tuner) (0.4.0)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow>=2.0->keras-tuner) (3.1.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow>=2.0->keras-tuner) (2.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow>=2.0->keras-tuner) (1.15.0)
Requirement already satisfied: tensorboard<2.12,>=2.11 in /usr/local/lib/python3.9/dist-packages (from tensorflow>=2.0->keras-tuner) (2.11.2)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow>=2.0->keras-tuner) (1.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.9/dist-packages (from tensorflow>=2.0->keras-tuner) (57.4.0)
Requirement already satisfied: keras<2.12,>=2.11.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow>=2.0->keras-tuner) (2.11.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow>=2.0->keras-tuner) (1.6.3)
Requirement already satisfied: flatbuffers>=2.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow>=2.0->keras-tuner) (23.3.3)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow>=2.0->keras-tuner) (15.0.6.1)
Requirement already satisfied: typing-extensions>=3.6.6 in /usr/local/lib/python3.9/dist-packages (from tensorflow>=2.0->keras-tuner) (4.5.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.9/dist-packages (from tensorflow>=2.0->keras-tuner) (1.51.3)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.9/dist-packages (from tensorflow>=2.0->keras-tuner) (1.22.4)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/lib/python3.9/dist-packages (from tensorflow>=2.0->keras-tuner) (3.3.0)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in /usr/local/lib/python3.9/dist-packages (from tensorflow>=2.0->keras-tuner) (3.19.6)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in /usr/local/lib/python3.9/dist-packages (from tensorflow>=2.0->keras-tuner) (0.31.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.9/dist-packages (from tensorflow>=2.0->keras-tuner) (1.4.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.9/dist-packages (from ipython->keras-tuner) (4.4.2)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from ipython->keras-tuner) (2.0.10)
Requirement already satisfied: pygments in /usr/local/lib/python3.9/dist-packages (from ipython->keras-tuner) (2.6.1)
Requirement already satisfied: pexpect in /usr/local/lib/python3.9/dist-packages (from ipython->keras-tuner) (4.8.0)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.9/dist-packages (from ipython->keras-tuner) (5.7.1)
Collecting jedi>=0.10
  Downloading jedi-0.18.2-py2.py3-none-any.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 39.8 MB/s eta 0:00:00
Requirement already satisfied: pickleshare in /usr/local/lib/python3.9/dist-packages (from ipython->keras-tuner) (0.7.5)
Requirement already satisfied: backcall in /usr/local/lib/python3.9/dist-packages (from ipython->keras-tuner) (0.2.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.9/dist-packages (from requests->keras-tuner) (2022.12.7)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.9/dist-packages (from requests->keras-tuner) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.9/dist-packages (from requests->keras-tuner) (1.26.14)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.9/dist-packages (from requests->keras-tuner) (4.0.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.9/dist-packages (from astunparse>=1.6.0->tensorflow>=2.0->keras-tuner) (0.38.4)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.9/dist-packages (from jedi>=0.10->ipython->keras-tuner) (0.8.3)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.9/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython->keras-tuner) (0.2.6)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.9/dist-packages (from tensorboard<2.12,>=2.11->tensorflow>=2.0->keras-tuner) (2.16.2)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.9/dist-packages (from tensorboard<2.12,>=2.11->tensorflow>=2.0->keras-tuner) (3.4.1)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /usr/local/lib/python3.9/dist-packages (from tensorboard<2.12,>=2.11->tensorflow>=2.0->keras-tuner) (0.6.1)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.9/dist-packages (from tensorboard<2.12,>=2.11->tensorflow>=2.0->keras-tuner) (0.4.6)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.9/dist-packages (from tensorboard<2.12,>=2.11->tensorflow>=2.0->keras-tuner) (1.8.1)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.9/dist-packages (from tensorboard<2.12,>=2.11->tensorflow>=2.0->keras-tuner) (2.2.3)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.9/dist-packages (from pexpect->ipython->keras-tuner) (0.7.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.9/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow>=2.0->keras-tuner) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.9/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow>=2.0->keras-tuner) (4.9)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.9/dist-packages (from google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow>=2.0->keras-tuner) (5.3.0)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.9/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.12,>=2.11->tensorflow>=2.0->keras-tuner) (1.3.1)
Requirement already satisfied: importlib-metadata>=4.4 in /usr/local/lib/python3.9/dist-packages (from markdown>=2.6.8->tensorboard<2.12,>=2.11->tensorflow>=2.0->keras-tuner) (6.0.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in /usr/local/lib/python3.9/dist-packages (from werkzeug>=1.0.1->tensorboard<2.12,>=2.11->tensorflow>=2.0->keras-tuner) (2.1.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.9/dist-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard<2.12,>=2.11->tensorflow>=2.0->keras-tuner) (3.15.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.9/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.12,>=2.11->tensorflow>=2.0->keras-tuner) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.9/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard<2.12,>=2.11->tensorflow>=2.0->keras-tuner) (3.2.2)
Installing collected packages: kt-legacy, jedi, keras-tuner
Successfully installed jedi-0.18.2 keras-tuner-1.3.0 kt-legacy-1.0.4

In [2]:
#import dependencies
import pandas as pd
from sqlalchemy import create_engine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

#set up connection to databse
from sqlalchemy import create_engine


protocol = 'postgresql'
username = 'postgres'
password = 'administrator'
host = 'wine.corp16oy9wyq.us-east-1.rds.amazonaws.com'
port = 5432
database = 'wine'

rds_connection_string = f'{protocol}://{username}:{password}@{host}:{port}/{database}'
        
engine = create_engine(rds_connection_string)
conn = engine.connect()

In [3]:
#Retrieve Data from RDS SQL Database
data = pd.read_sql("SELECT * FROM wine_data", conn)
# data = pd.read_csv("Data/full_data.csv",index_col=0)
data

,wine_id,country,description,designation,points,price,province,region_1,region_2,taster_name,...,max_temp,precip,humidity,heat_index,latitude_y,longitude_y,elevation,review_neg,review_neu,review_pos
0,1,US,"Overripe and Porty, with raisin, prune and cho...",Reserve,81,37.0,California,Paso Robles,Central Coast,None,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.000,0.000,0.829,0.171
1,2,US,"Strong aromas of blueberry paste, cracked pepp...",Paso Bordo Reserve,92,69.0,California,Paso Robles,Central Coast,Matt Kettmann,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.000,0.000,0.805,0.195
2,3,US,A vegetal note drags down the enjoyment. On th...,Reserve,84,39.0,California,Paso Robles,Central Coast,None,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.000,0.129,0.710,0.162
3,4,US,Larry Stanton patiently waits to release the w...,La Terraza Bloc Reserve,93,59.0,California,Paso Robles,Central Coast,Matt Kettmann,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.000,0.039,0.865,0.096
4,5,US,"High alcohol gives the wine heat, especially i...",La Tertazza Bloc Reserve,85,39.0,California,Paso Robles,Central Coast,None,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.000,0.000,0.895,0.105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48842,48843,US,This spicy wine offers peppery strawberry flav...,Solare,87,26.0,Washington,Columbia Valley (WA),Columbia Valley,Paul Gregutt,...,102.5,27.15,74.02,105.2,0.077000,0.807000,0.115,0.077,0.807,0.115
48843,48844,US,This wine is partially barrel fermented and bl...,None,89,20.0,Washington,Columbia Gorge (WA),Washington Other,Sean P. Sullivan,...,115.0,16.61,57.52,106.4,0.000000,0.927000,0.073,0.000,0.927,0.073
48844,48845,US,"Clean and fresh, this pure varietal Grenache c...",Lonesome Spring Ranch,88,25.0,Washington,Yakima Valley,Columbia Valley,Paul Gregutt,...,112.9,6.90,57.53,107.1,0.059000,0.743000,0.197,0.059,0.743,0.197
48845,48846,US,The seventh edition of this popular blend retu...,Red,88,20.0,Washington,Columbia Valley (WA),Columbia Valley,Paul Gregutt,...,114.5,17.07,57.74,106.0,0.000000,0.897000,0.103,0.000,0.897,0.103
48846,48847,US,"The aromas pop, with notes of freshly ground w...",Boushey Vineyard,91,49.0,Washington,Yakima Valley,Columbia Valley,Sean P. Sullivan,...,113.0,6.89,57.78,107.5,0.000000,0.879000,0.121,0.000,0.879,0.121

In [4]:
print(data.nunique())

wine_id                  48847
country                      1
description              45206
designation              12744
points                      21
price                      158
province                     4
region_1                   201
region_2                    17
taster_name                 13
taster_twitter_handle       12
title                    45026
variety                    252
winery_name               4803
latitude_x                3032
longitude_x               3000
min_temp                   360
max_temp                   261
precip                    1564
humidity                  1306
heat_index                 242
latitude_y                2973
longitude_y               3185
elevation                  936
review_neg                 254
review_neu                 476
review_pos                 465
dtype: int64

In [5]:
data.drop(["country", "description", "designation","taster_name", "taster_twitter_handle", "title" ], axis=1, inplace=True)
data.head()

,wine_id,points,price,province,region_1,region_2,variety,winery_name,latitude_x,longitude_x,...,max_temp,precip,humidity,heat_index,latitude_y,longitude_y,elevation,review_neg,review_neu,review_pos
0,1,81,37.0,California,Paso Robles,Central Coast,Merlot,Cerro Prieto winery,33.343447,-117.203325,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.000,0.829,0.171
1,2,92,69.0,California,Paso Robles,Central Coast,Cabernet Sauvignon,Cerro Prieto winery,33.343447,-117.203325,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.000,0.805,0.195
2,3,84,39.0,California,Paso Robles,Central Coast,Pinot Noir,Cerro Prieto winery,33.343447,-117.203325,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.129,0.710,0.162
3,4,93,59.0,California,Paso Robles,Central Coast,Syrah,Cerro Prieto winery,33.343447,-117.203325,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.039,0.865,0.096
4,5,85,39.0,California,Paso Robles,Central Coast,Syrah,Cerro Prieto winery,33.343447,-117.203325,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.000,0.895,0.105

In [6]:
#create bins for price ranges
def price_to_range(price): 
  if (price < 20): 
    return 0 
  elif (price >20) and (price <= 45):
    return 1
  elif (price >45) and (price <= 80):
    return 2 
  elif (price >80) and (price <= 100):
    return 3
  elif (price >140) and (price <= 300): 
    return 4
  else: 
    return 5
  
data["price"] = data["price"].apply(price_to_range)
data = data.rename(columns={"price": "price_range"})
data.head()

,wine_id,points,price_range,province,region_1,region_2,variety,winery_name,latitude_x,longitude_x,...,max_temp,precip,humidity,heat_index,latitude_y,longitude_y,elevation,review_neg,review_neu,review_pos
0,1,81,1,California,Paso Robles,Central Coast,Merlot,Cerro Prieto winery,33.343447,-117.203325,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.000,0.829,0.171
1,2,92,2,California,Paso Robles,Central Coast,Cabernet Sauvignon,Cerro Prieto winery,33.343447,-117.203325,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.000,0.805,0.195
2,3,84,1,California,Paso Robles,Central Coast,Pinot Noir,Cerro Prieto winery,33.343447,-117.203325,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.129,0.710,0.162
3,4,93,2,California,Paso Robles,Central Coast,Syrah,Cerro Prieto winery,33.343447,-117.203325,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.039,0.865,0.096
4,5,85,1,California,Paso Robles,Central Coast,Syrah,Cerro Prieto winery,33.343447,-117.203325,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.000,0.895,0.105

In [7]:
def points_to_range(points): 
  if (points >=90):
    return 0
  else: 
    return 1
  
data["points"] = data["points"].apply(points_to_range)
data = data.rename(columns={"points": "point_range"})
data.head()

,wine_id,point_range,price_range,province,region_1,region_2,variety,winery_name,latitude_x,longitude_x,...,max_temp,precip,humidity,heat_index,latitude_y,longitude_y,elevation,review_neg,review_neu,review_pos
0,1,1,1,California,Paso Robles,Central Coast,Merlot,Cerro Prieto winery,33.343447,-117.203325,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.000,0.829,0.171
1,2,0,2,California,Paso Robles,Central Coast,Cabernet Sauvignon,Cerro Prieto winery,33.343447,-117.203325,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.000,0.805,0.195
2,3,1,1,California,Paso Robles,Central Coast,Pinot Noir,Cerro Prieto winery,33.343447,-117.203325,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.129,0.710,0.162
3,4,0,2,California,Paso Robles,Central Coast,Syrah,Cerro Prieto winery,33.343447,-117.203325,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.039,0.865,0.096
4,5,1,1,California,Paso Robles,Central Coast,Syrah,Cerro Prieto winery,33.343447,-117.203325,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.000,0.895,0.105

In [8]:
variety_values = data["variety"].value_counts()
variety_value_counts = variety_values[variety_values > 100]
variety_value_counts

Pinot Noir                  8868
Cabernet Sauvignon          6811
Chardonnay                  6241
Syrah                       2978
Red Blend                   2548
Zinfandel                   2515
Merlot                      2137
Sauvignon Blanc             1891
Bordeaux-style Red Blend    1664
Riesling                    1550
Cabernet Franc               830
Pinot Gris                   764
RosÃ©                        701
RhÃ´ne-style Red Blend       649
Petite Sirah                 643
Viognier                     640
Sparkling Blend              608
White Blend                  523
Malbec                       491
Grenache                     489
Sangiovese                   365
Pinot Grigio                 321
Tempranillo                  299
GewÃ¼rztraminer              279
Meritage                     215
Barbera                      203
RhÃ´ne-style White Blend     198
MourvÃ¨dre                   181
Pinot Blanc                  178
Petit Verdot                 171
G-S-M                        138
Roussanne                    123
Grenache Blanc               115
AlbariÃ±o                    109
Name: variety, dtype: int64

In [9]:
# Choose a cutoff value and create a list of varieties to be replaced
cutoff = 1500
variety_types_to_replace = list(variety_values[variety_values <= cutoff].index)

# Replace in dataframe
for variety in variety_types_to_replace:
   data['variety'] = data['variety'].replace(variety,"Other")

# Check to make sure binning was successful
data['variety'].value_counts()

Other                       11644
Pinot Noir                   8868
Cabernet Sauvignon           6811
Chardonnay                   6241
Syrah                        2978
Red Blend                    2548
Zinfandel                    2515
Merlot                       2137
Sauvignon Blanc              1891
Bordeaux-style Red Blend     1664
Riesling                     1550
Name: variety, dtype: int64

In [10]:
winery_values = data["winery_name"].value_counts()
winery_value_counts = winery_values[winery_values > 100]
winery_value_counts

Testarossa winery               217
Williams Selyem winery          198
Chateau Ste. Michelle winery    193
Columbia Crest winery           158
Siduri winery                   126
Gary Farrell winery             125
Kendall-Jackson winery          118
Lynmar winery                   118
Robert Mondavi winery           112
Fess Parker winery              108
Iron Horse winery               106
Foxen winery                    103
Maryhill winery                 102
Chehalem winery                 102
Kunde winery                    101
Name: winery_name, dtype: int64

In [11]:
data.drop(['winery_name'], axis=1, inplace=True)
data.columns

Index(['wine_id', 'point_range', 'price_range', 'province', 'region_1',
       'region_2', 'variety', 'latitude_x', 'longitude_x', 'min_temp',
       'max_temp', 'precip', 'humidity', 'heat_index', 'latitude_y',
       'longitude_y', 'elevation', 'review_neg', 'review_neu', 'review_pos'],
      dtype='object')

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
X_dummies = pd.get_dummies(data)
X_dummies

,wine_id,point_range,price_range,latitude_x,longitude_x,min_temp,max_temp,precip,humidity,heat_index,...,variety_Cabernet Sauvignon,variety_Chardonnay,variety_Merlot,variety_Other,variety_Pinot Noir,variety_Red Blend,variety_Riesling,variety_Sauvignon Blanc,variety_Syrah,variety_Zinfandel
0,1,1,1,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,...,0,0,1,0,0,0,0,0,0,0
1,2,0,2,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,...,1,0,0,0,0,0,0,0,0,0
2,3,1,1,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,...,0,0,0,0,1,0,0,0,0,0
3,4,0,2,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,...,0,0,0,0,0,0,0,0,1,0
4,5,1,1,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48842,48843,1,1,47.766300,-122.148337,15.4,102.5,27.15,74.02,105.2,...,0,0,0,1,0,0,0,0,0,0
48843,48844,1,5,46.068561,-118.342366,-0.9,115.0,16.61,57.52,106.4,...,0,0,0,0,0,0,0,1,0,0
48844,48845,1,1,46.557883,-120.660862,2.0,112.9,6.90,57.53,107.1,...,0,0,0,1,0,0,0,0,0,0
48845,48846,1,5,46.003999,-118.371124,-0.8,114.5,17.07,57.74,106.0,...,0,0,0,0,0,1,0,0,0,0
48846,48847,0,2,46.584583,-120.530667,2.0,113.0,6.89,57.78,107.5,...,0,0,0,1,0,0,0,0,0,0

In [13]:
# Split our preprocessed data into our features and target arrays
X = X_dummies.drop('point_range',axis=1).values
y = data['point_range'].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [14]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [15]:
# Create a method that creates a new Sequential model with hyperparameter options
def create_model(hp):
    nn_model = tf.keras.models.Sequential()

    # Allow kerastuner to decide which activation function to use in hidden layers
    activation = hp.Choice('activation',['relu','tanh','sigmoid'])
    
    # Allow kerastuner to decide number of neurons in first layer
    nn_model.add(tf.keras.layers.Dense(units=hp.Int('first_units',
        min_value=1,
        max_value=500,
        step=35), activation=activation, input_dim=len(X_train[0])))

    # Allow kerastuner to decide number of hidden layers and neurons in hidden layers
    for i in range(hp.Int('num_layers', 1, 6)):
        nn_model.add(tf.keras.layers.Dense(units=hp.Int('units_' + str(i),
            min_value=1,
            max_value=500,
            step=35),
            activation=activation))
    
    nn_model.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

    # Compile the model
    nn_model.compile(loss="binary_crossentropy", optimizer='adam', metrics=["accuracy"])
    
    return nn_model

In [16]:
# Import the kerastuner library
import keras_tuner as kt

tuner = kt.Hyperband(
    create_model,
    objective="val_accuracy",
    max_epochs=30,
    hyperband_iterations=2)

In [17]:
# Run the kerastuner search for best hyperparameters
tuner.search(X_train_scaled,y_train,epochs=30,validation_data=(X_test_scaled,y_test))

Trial 180 Complete [00h 05m 24s]
val_accuracy: 0.7283819317817688

Best val_accuracy So Far: 0.7301015257835388
Total elapsed time: 03h 50m 36s

In [18]:
# Get best model hyperparameters
best_hyper = tuner.get_best_hyperparameters(1)[0]
best_hyper.values

{'activation': 'relu',
 'first_units': 316,
 'num_layers': 1,
 'units_0': 456,
 'units_1': 456,
 'units_2': 281,
 'units_3': 491,
 'units_4': 246,
 'units_5': 456,
 'tuner/epochs': 30,
 'tuner/initial_epoch': 0,
 'tuner/bracket': 0,
 'tuner/round': 0}

In [19]:
# Evaluate best model against full test data
best_model = tuner.get_best_models(1)[0]
model_loss, model_accuracy = best_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

382/382 - 1s - loss: 0.5555 - accuracy: 0.7301 - 1s/epoch - 3ms/step
Loss: 0.5555452108383179, Accuracy: 0.7301015257835388