# Data Preprocessing

In [1]:
#import dependencies
import pandas as pd
from sqlalchemy import create_engine
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

#set up connection to databse
from sqlalchemy import create_engine


protocol = 'postgresql'
username = 'postgres'
password = 'administrator'
host = 'wine.corp16oy9wyq.us-east-1.rds.amazonaws.com'
port = 5432
database = 'wine'

rds_connection_string = f'{protocol}://{username}:{password}@{host}:{port}/{database}'
        
engine = create_engine(rds_connection_string)
conn = engine.connect()

In [2]:
#Retrieve Data from RDS SQL Database
data = pd.read_sql("SELECT * FROM wine_data", conn)
data.head()

,wine_id,country,description,designation,points,price,province,region_1,region_2,taster_name,...,max_temp,precip,humidity,heat_index,latitude_y,longitude_y,elevation,review_neg,review_neu,review_pos
0,1,US,"Overripe and Porty, with raisin, prune and cho...",Reserve,81,37.0,California,Paso Robles,Central Coast,None,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.000,0.829,0.171
1,2,US,"Strong aromas of blueberry paste, cracked pepp...",Paso Bordo Reserve,92,69.0,California,Paso Robles,Central Coast,Matt Kettmann,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.000,0.805,0.195
2,3,US,A vegetal note drags down the enjoyment. On th...,Reserve,84,39.0,California,Paso Robles,Central Coast,None,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.129,0.710,0.162
3,4,US,Larry Stanton patiently waits to release the w...,La Terraza Bloc Reserve,93,59.0,California,Paso Robles,Central Coast,Matt Kettmann,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.039,0.865,0.096
4,5,US,"High alcohol gives the wine heat, especially i...",La Tertazza Bloc Reserve,85,39.0,California,Paso Robles,Central Coast,None,...,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.000,0.895,0.105

In [3]:
print(data.nunique())

wine_id                  48847
country                      1
description              45206
designation              12744
points                      21
price                      158
province                     4
region_1                   201
region_2                    17
taster_name                 13
taster_twitter_handle       12
title                    45026
variety                    252
winery_name               4803
latitude_x                3032
longitude_x               3000
min_temp                   360
max_temp                   261
precip                    1564
humidity                  1306
heat_index                 242
latitude_y                2973
longitude_y               3185
elevation                  936
review_neg                 254
review_neu                 476
review_pos                 465
dtype: int64

In [4]:
data.drop(["wine_id", "country", "description", "designation","taster_name", "taster_twitter_handle", "title" ], axis=1, inplace=True)
data.head()

,points,price,province,region_1,region_2,variety,winery_name,latitude_x,longitude_x,min_temp,max_temp,precip,humidity,heat_index,latitude_y,longitude_y,elevation,review_neg,review_neu,review_pos
0,81,37.0,California,Paso Robles,Central Coast,Merlot,Cerro Prieto winery,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.000,0.829,0.171
1,92,69.0,California,Paso Robles,Central Coast,Cabernet Sauvignon,Cerro Prieto winery,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.000,0.805,0.195
2,84,39.0,California,Paso Robles,Central Coast,Pinot Noir,Cerro Prieto winery,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.129,0.710,0.162
3,93,59.0,California,Paso Robles,Central Coast,Syrah,Cerro Prieto winery,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.039,0.865,0.096
4,85,39.0,California,Paso Robles,Central Coast,Syrah,Cerro Prieto winery,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.000,0.895,0.105

In [5]:
#create bins for price ranges
def price_to_range(price): 
  if (price < 20): 
    return 0 
  elif (price >20) and (price <= 45):
    return 1
  elif (price >45) and (price <= 80):
    return 2 
  elif (price >80) and (price <= 100):
    return 3
  elif (price >140) and (price <= 300): 
    return 4
  else: 
    return 5
  
data["price"] = data["price"].apply(price_to_range)
data = data.rename(columns={"price": "price_range"})
data.head()

,points,price_range,province,region_1,region_2,variety,winery_name,latitude_x,longitude_x,min_temp,max_temp,precip,humidity,heat_index,latitude_y,longitude_y,elevation,review_neg,review_neu,review_pos
0,81,1,California,Paso Robles,Central Coast,Merlot,Cerro Prieto winery,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.000,0.829,0.171
1,92,2,California,Paso Robles,Central Coast,Cabernet Sauvignon,Cerro Prieto winery,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.000,0.805,0.195
2,84,1,California,Paso Robles,Central Coast,Pinot Noir,Cerro Prieto winery,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.129,0.710,0.162
3,93,2,California,Paso Robles,Central Coast,Syrah,Cerro Prieto winery,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.039,0.865,0.096
4,85,1,California,Paso Robles,Central Coast,Syrah,Cerro Prieto winery,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.000,0.895,0.105

In [6]:
def points_to_range(points): 
  if (points >= 90):
    return 0
  else: 
    return 1
  
data["points"] = data["points"].apply(points_to_range)
data = data.rename(columns={"points": "point_range"})
data.head()

,point_range,price_range,province,region_1,region_2,variety,winery_name,latitude_x,longitude_x,min_temp,max_temp,precip,humidity,heat_index,latitude_y,longitude_y,elevation,review_neg,review_neu,review_pos
0,1,1,California,Paso Robles,Central Coast,Merlot,Cerro Prieto winery,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.000,0.829,0.171
1,0,2,California,Paso Robles,Central Coast,Cabernet Sauvignon,Cerro Prieto winery,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.000,0.805,0.195
2,1,1,California,Paso Robles,Central Coast,Pinot Noir,Cerro Prieto winery,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.129,0.710,0.162
3,0,2,California,Paso Robles,Central Coast,Syrah,Cerro Prieto winery,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.039,0.865,0.096
4,1,1,California,Paso Robles,Central Coast,Syrah,Cerro Prieto winery,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,33.343447,-117.203325,190.0,0.000,0.895,0.105

In [7]:
data["point_range"].value_counts()

1    28236
0    20611
Name: point_range, dtype: int64

In [8]:
variety_values = data["variety"].value_counts()
variety_value_counts = variety_values[variety_values > 100]
variety_value_counts

Pinot Noir                  8868
Cabernet Sauvignon          6811
Chardonnay                  6241
Syrah                       2978
Red Blend                   2548
Zinfandel                   2515
Merlot                      2137
Sauvignon Blanc             1891
Bordeaux-style Red Blend    1664
Riesling                    1550
Cabernet Franc               830
Pinot Gris                   764
RosÃ©                        701
RhÃ´ne-style Red Blend       649
Petite Sirah                 643
Viognier                     640
Sparkling Blend              608
White Blend                  523
Malbec                       491
Grenache                     489
Sangiovese                   365
Pinot Grigio                 321
Tempranillo                  299
GewÃ¼rztraminer              279
Meritage                     215
Barbera                      203
RhÃ´ne-style White Blend     198
MourvÃ¨dre                   181
Pinot Blanc                  178
Petit Verdot                 171
G-S-M                        138
Roussanne                    123
Grenache Blanc               115
AlbariÃ±o                    109
Name: variety, dtype: int64

In [9]:
# Choose a cutoff value and create a list of varieties to be replaced
cutoff = 1500
variety_types_to_replace = list(variety_values[variety_values <= cutoff].index)

# Replace in dataframe
for variety in variety_types_to_replace:
   data['variety'] = data['variety'].replace(variety,"Other")

# Check to make sure binning was successful
data['variety'].value_counts()

Other                       11644
Pinot Noir                   8868
Cabernet Sauvignon           6811
Chardonnay                   6241
Syrah                        2978
Red Blend                    2548
Zinfandel                    2515
Merlot                       2137
Sauvignon Blanc              1891
Bordeaux-style Red Blend     1664
Riesling                     1550
Name: variety, dtype: int64

In [10]:
winery_values = data["winery_name"].value_counts()
winery_value_counts = winery_values[winery_values > 100]
winery_value_counts

Testarossa winery               217
Williams Selyem winery          198
Chateau Ste. Michelle winery    193
Columbia Crest winery           158
Siduri winery                   126
Gary Farrell winery             125
Kendall-Jackson winery          118
Lynmar winery                   118
Robert Mondavi winery           112
Fess Parker winery              108
Iron Horse winery               106
Foxen winery                    103
Maryhill winery                 102
Chehalem winery                 102
Kunde winery                    101
Name: winery_name, dtype: int64

In [11]:
data.drop(['winery_name'], axis=1, inplace=True)
data.columns

Index(['point_range', 'price_range', 'province', 'region_1', 'region_2',
       'variety', 'latitude_x', 'longitude_x', 'min_temp', 'max_temp',
       'precip', 'humidity', 'heat_index', 'latitude_y', 'longitude_y',
       'elevation', 'review_neg', 'review_neu', 'review_pos'],
      dtype='object')

In [12]:
# Convert categorical data to numeric with `pd.get_dummies`
X_dummies = pd.get_dummies(data)
X_dummies

,point_range,price_range,latitude_x,longitude_x,min_temp,max_temp,precip,humidity,heat_index,latitude_y,...,variety_Cabernet Sauvignon,variety_Chardonnay,variety_Merlot,variety_Other,variety_Pinot Noir,variety_Red Blend,variety_Riesling,variety_Sauvignon Blanc,variety_Syrah,variety_Zinfandel
0,1,1,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,33.343447,...,0,0,1,0,0,0,0,0,0,0
1,0,2,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,33.343447,...,1,0,0,0,0,0,0,0,0,0
2,1,1,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,33.343447,...,0,0,0,0,1,0,0,0,0,0
3,0,2,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,33.343447,...,0,0,0,0,0,0,0,0,1,0
4,1,1,33.343447,-117.203325,34.4,100.4,7.94,65.69,101.7,33.343447,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48842,1,1,47.766300,-122.148337,15.4,102.5,27.15,74.02,105.2,0.077000,...,0,0,0,1,0,0,0,0,0,0
48843,1,5,46.068561,-118.342366,-0.9,115.0,16.61,57.52,106.4,0.000000,...,0,0,0,0,0,0,0,1,0,0
48844,1,1,46.557883,-120.660862,2.0,112.9,6.90,57.53,107.1,0.059000,...,0,0,0,1,0,0,0,0,0,0
48845,1,5,46.003999,-118.371124,-0.8,114.5,17.07,57.74,106.0,0.000000,...,0,0,0,0,0,1,0,0,0,0
48846,0,2,46.584583,-120.530667,2.0,113.0,6.89,57.78,107.5,0.000000,...,0,0,0,1,0,0,0,0,0,0

In [13]:
# Split our preprocessed data into our features and target arrays
X = X_dummies.drop('point_range',axis=1).values
y = data['point_range'].values

from sklearn.decomposition import PCA
pca = PCA(n_components=0.99)
pca_data = pca.fit_transform(X_dummies)
pca_data_df=pd.DataFrame(pca_data)
pca_data_df

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(pca_data_df, y, random_state=42)

In [14]:
X_train.shape

(36635, 3)

In [22]:
X_test.shape

(12212, 3)

In [23]:
# Create a StandardScaler instances
scaler = StandardScaler()
# from sklearn.preprocessing import MinMaxScaler
# scaler = MinMaxScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [24]:
len(X_train[0])

36635

In [25]:
pca_data.shape

(48847, 3)

In [26]:
len(pca_data[0])

3

# Machine Learning

In [27]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
input_features = len(pca_data[0])
print("Input Features =",input_features)
nodes1 = 10
print("Hidden Nodes - Layer 1 =", nodes1)
nodes3 = 1
print("Hidden Nodes - Layer 3 =", nodes3)
nn = tf.keras.models.Sequential()
# First hidden layer
nn.add(tf.keras.layers.Dense(units=nodes1, activation="relu", input_dim=input_features))
# Output layer
nn.add(tf.keras.layers.Dense(units=nodes3, activation="sigmoid"))
# Check the structure of the model
nn.summary()

Input Features = 3
Hidden Nodes - Layer 1 = 10
Hidden Nodes - Layer 3 = 1
Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_2 (Dense)             (None, 10)                40

 dense_3 (Dense)             (None, 1)                 11

=================================================================
Total params: 51
Trainable params: 51
Non-trainable params: 0
_________________________________________________________________

In [28]:
# # Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [29]:
# # Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100)

Epoch 1/100
1145/1145 [==============================] - 4s 2ms/step - loss: 0.6790 - accuracy: 0.5680
Epoch 2/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6682 - accuracy: 0.5770
Epoch 3/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6669 - accuracy: 0.5740
Epoch 4/100
1145/1145 [==============================] - 3s 3ms/step - loss: 0.6661 - accuracy: 0.5758
Epoch 5/100
1145/1145 [==============================] - 6s 5ms/step - loss: 0.6655 - accuracy: 0.5791
Epoch 6/100
1145/1145 [==============================] - 6s 5ms/step - loss: 0.6654 - accuracy: 0.5770
Epoch 7/100
1145/1145 [==============================] - 4s 4ms/step - loss: 0.6651 - accuracy: 0.5795
Epoch 8/100
1145/1145 [==============================] - 3s 3ms/step - loss: 0.6650 - accuracy: 0.5784
Epoch 9/100
1145/1145 [==============================] - 3s 3ms/step - loss: 0.6648 - accuracy: 0.5798
Epoch 10/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6647 - accuracy: 0.5839
Epoch 11/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6645 - accuracy: 0.5826
Epoch 12/100
1145/1145 [==============================] - 3s 2ms/step - loss: 0.6645 - accuracy: 0.5838
Epoch 13/100
1145/1145 [==============================] - 3s 2ms/step - loss: 0.6644 - accuracy: 0.5847
Epoch 14/100
1145/1145 [==============================] - 3s 3ms/step - loss: 0.6645 - accuracy: 0.5826
Epoch 15/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6644 - accuracy: 0.5833
Epoch 16/100
1145/1145 [==============================] - 3s 2ms/step - loss: 0.6644 - accuracy: 0.5821
Epoch 17/100
1145/1145 [==============================] - 4s 4ms/step - loss: 0.6642 - accuracy: 0.5856
Epoch 18/100
1145/1145 [==============================] - 3s 2ms/step - loss: 0.6642 - accuracy: 0.5842
Epoch 19/100
1145/1145 [==============================] - 3s 3ms/step - loss: 0.6641 - accuracy: 0.5822
Epoch 20/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6640 - accuracy: 0.5850
Epoch 21/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6640 - accuracy: 0.5837
Epoch 22/100
1145/1145 [==============================] - 4s 3ms/step - loss: 0.6640 - accuracy: 0.5834
Epoch 23/100
1145/1145 [==============================] - 3s 3ms/step - loss: 0.6638 - accuracy: 0.5872
Epoch 24/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6637 - accuracy: 0.5849
Epoch 25/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6636 - accuracy: 0.5867
Epoch 26/100
1145/1145 [==============================] - 3s 2ms/step - loss: 0.6635 - accuracy: 0.5881
Epoch 27/100
1145/1145 [==============================] - 3s 2ms/step - loss: 0.6635 - accuracy: 0.5886
Epoch 28/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6634 - accuracy: 0.5899
Epoch 29/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6634 - accuracy: 0.5897
Epoch 30/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6633 - accuracy: 0.5882
Epoch 31/100
1145/1145 [==============================] - 3s 2ms/step - loss: 0.6633 - accuracy: 0.5895
Epoch 32/100
1145/1145 [==============================] - 4s 3ms/step - loss: 0.6632 - accuracy: 0.5891
Epoch 33/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6634 - accuracy: 0.5891
Epoch 34/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6632 - accuracy: 0.5904
Epoch 35/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6631 - accuracy: 0.5920
Epoch 36/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6631 - accuracy: 0.5909
Epoch 37/100
1145/1145 [==============================] - 3s 2ms/step - loss: 0.6632 - accuracy: 0.5902
Epoch 38/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6630 - accuracy: 0.5895
Epoch 39/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6631 - accuracy: 0.5894
Epoch 40/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6631 - accuracy: 0.5906
Epoch 41/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6630 - accuracy: 0.5900
Epoch 42/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6629 - accuracy: 0.5912
Epoch 43/100
1145/1145 [==============================] - 3s 3ms/step - loss: 0.6629 - accuracy: 0.5897
Epoch 44/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6630 - accuracy: 0.5886
Epoch 45/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6629 - accuracy: 0.5881
Epoch 46/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6630 - accuracy: 0.5895
Epoch 47/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6630 - accuracy: 0.5905
Epoch 48/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6628 - accuracy: 0.5920
Epoch 49/100
1145/1145 [==============================] - 3s 2ms/step - loss: 0.6629 - accuracy: 0.5894
Epoch 50/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6628 - accuracy: 0.5887
Epoch 51/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6629 - accuracy: 0.5892
Epoch 52/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6628 - accuracy: 0.5912
Epoch 53/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6628 - accuracy: 0.5912
Epoch 54/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6628 - accuracy: 0.5913
Epoch 55/100
1145/1145 [==============================] - 3s 2ms/step - loss: 0.6626 - accuracy: 0.5881
Epoch 56/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6628 - accuracy: 0.5894
Epoch 57/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6627 - accuracy: 0.5902
Epoch 58/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6626 - accuracy: 0.5901
Epoch 59/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6626 - accuracy: 0.5908
Epoch 60/100
1145/1145 [==============================] - 3s 2ms/step - loss: 0.6627 - accuracy: 0.5884
Epoch 61/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6626 - accuracy: 0.5903
Epoch 62/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6624 - accuracy: 0.5873
Epoch 63/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6624 - accuracy: 0.5909
Epoch 64/100
1145/1145 [==============================] - 3s 2ms/step - loss: 0.6624 - accuracy: 0.5908
Epoch 65/100
1145/1145 [==============================] - 4s 3ms/step - loss: 0.6625 - accuracy: 0.5891
Epoch 66/100
1145/1145 [==============================] - 8s 7ms/step - loss: 0.6624 - accuracy: 0.5897
Epoch 67/100
1145/1145 [==============================] - 3s 2ms/step - loss: 0.6624 - accuracy: 0.5887
Epoch 68/100
1145/1145 [==============================] - 3s 2ms/step - loss: 0.6623 - accuracy: 0.5902
Epoch 69/100
1145/1145 [==============================] - 3s 2ms/step - loss: 0.6624 - accuracy: 0.5921
Epoch 70/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6624 - accuracy: 0.5896
Epoch 71/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6622 - accuracy: 0.5901
Epoch 72/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6623 - accuracy: 0.5886
Epoch 73/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6622 - accuracy: 0.5918
Epoch 74/100
1145/1145 [==============================] - 3s 3ms/step - loss: 0.6621 - accuracy: 0.5909
Epoch 75/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6623 - accuracy: 0.5906
Epoch 76/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6621 - accuracy: 0.5891
Epoch 77/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6621 - accuracy: 0.5897
Epoch 78/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6622 - accuracy: 0.5924
Epoch 79/100
1145/1145 [==============================] - 3s 2ms/step - loss: 0.6621 - accuracy: 0.5921
Epoch 80/100
1145/1145 [==============================] - 3s 2ms/step - loss: 0.6621 - accuracy: 0.5901
Epoch 81/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6620 - accuracy: 0.5902
Epoch 82/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6619 - accuracy: 0.5908
Epoch 83/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6620 - accuracy: 0.5929
Epoch 84/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6619 - accuracy: 0.5931
Epoch 85/100
1145/1145 [==============================] - 3s 3ms/step - loss: 0.6618 - accuracy: 0.5913
Epoch 86/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6618 - accuracy: 0.5922
Epoch 87/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6619 - accuracy: 0.5921
Epoch 88/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6619 - accuracy: 0.5923
Epoch 89/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6617 - accuracy: 0.5900
Epoch 90/100
1145/1145 [==============================] - 3s 2ms/step - loss: 0.6618 - accuracy: 0.5922
Epoch 91/100
1145/1145 [==============================] - 3s 2ms/step - loss: 0.6618 - accuracy: 0.5924
Epoch 92/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6618 - accuracy: 0.5937
Epoch 93/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6618 - accuracy: 0.5930
Epoch 94/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6617 - accuracy: 0.5919
Epoch 95/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6616 - accuracy: 0.5933
Epoch 96/100
1145/1145 [==============================] - 3s 3ms/step - loss: 0.6616 - accuracy: 0.5925
Epoch 97/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6616 - accuracy: 0.5932
Epoch 98/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6617 - accuracy: 0.5928
Epoch 99/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6616 - accuracy: 0.5941
Epoch 100/100
1145/1145 [==============================] - 2s 2ms/step - loss: 0.6616 - accuracy: 0.5922

In [31]:
# # Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

382/382 - 1s - loss: 0.6613 - accuracy: 0.5824 - 533ms/epoch - 1ms/step
Loss: 0.6612696647644043, Accuracy: 0.5823779702186584

# Saving Model

In [ ]:
# Export our model to HDF5 file
nn.save('../WineMLModel.h5')

##Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Fit the model
classifier = LogisticRegression().fit(X_train_scaled,y_train)

# Evaluate the model
y_pred = classifier.predict(X_test_scaled)
score = accuracy_score(y_test,y_pred)
score

0.5768915820504422

In [ ]:
print(f'Training Score: {classifier.score(X_train_scaled, y_train)}')
print(f'Testing Score: {classifier.score(X_test_scaled, y_test)}')

Training Score: 0.578408625631227
Testing Score: 0.5768915820504422

##Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier
# create and fit the model
clf = RandomForestClassifier(random_state=42, n_estimators=100).fit(X_train_scaled, y_train)
# Evaluate the model
y_predict = clf.predict(X_test_scaled)
score = accuracy_score(y_test,y_predict)
score

0.8709466098919096

In [ ]:
print(f'Training Score: {clf.score(X_train_scaled, y_train)}')
print(f'Testing Score: {clf.score(X_test_scaled, y_test)}')

Training Score: 0.9948955916473318
Testing Score: 0.7578611202096299